# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Urx < Formula
  desc "Extracts urls from osint archives for security insights"
  homepage "https://github.com/hahwul/urx"
  url "https://github.com/hahwul/urx/archive/refs/tags/0.6.0.tar.gz"
  sha256 "fc125cffadef51c7824015131d0eaf600804fa7454b4cbbbe2402fc326916801"
  license "MIT"

  depends_on "rust"

  def install
    system "cargo build --release"
bin.install "target/release/urx"
  end

  test do
    system "{bin}/urx", "-V"
  end
end
