# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Urx < Formula
  desc "Extracts urls from osint archives for security insights"
  homepage "https://github.com/hahwul/urx"
  url "https://github.com/hahwul/urx/archive/refs/tags/0.4.0.tar.gz"
  sha256 "0aaf8352d5b7de19eabdb31e456d4f48d9825b587ff318cc767057ce95912e45"
  license "MIT"

  depends_on "rust"

  def install
    system "cargo build --release"
bin.install "target/release/urx"
  end

  test do
    system "{bin}/urx", "-V"
  end
end
