# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Urx < Formula
  desc "Extracts urls from osint archives for security insights"
  homepage "https://github.com/hahwul/urx"
  url "https://github.com/hahwul/urx/archive/refs/tags/0.3.0.tar.gz"
  sha256 "f993294e0cec17ec765e008a262443d845ac90688f6e4dea163e6701353ac083"
  license "MIT"

  depends_on "rust"

  def install
    system "cargo build --release"
bin.install "target/release/urx"
  end

  test do
    system "{bin}/urx", "-V"
  end
end
